module.exports = [
  ['components', '组件相关'],
  ['hooks', 'hook 相关'],
  ['utils', 'utils 相关'],
  ['styles', '样式相关'],
  ['ui', '用户界面调整'],
  ['auth', '对 auth 修改'],
  ['performance', '性能优化'],
  ['security', '安全性更新'],
  ['i18n', '国际化'],
  ['docs', '文档更新'],
  ['changelog', '更新日志'],
  ['arco-design', '对 arco-design 的调整'],
  ['deps', '项目依赖'],
  ['config', '配置相关'],
  ['test', '测试相关'],
  ['tools', '工具相关文件的修改'],
  ['experiments', '实验性功能'],
  ['egg', '小彩蛋，小惊喜'],
  ['backend', '后端相关更改'],
  ['workflows', '工作流相关文件更改'],
  ['other', '其他修改']
];
