module.exports = [
  { value: '🍻 init', name: '初始：初始提交' },
  { value: '✨ feat', name: '特性：新的特性' },
  { value: '🐛 fix', name: '修复：修复Bug' },
  { value: '📚 docs', name: '文档：变更的只有文档' },
  { value: '💅 style', name: '格式：空格、分号等格式修复' },
  { value: '♻️ refactor', name: '重构：代码重构，注意和特性、修复区分开' },
  { value: '⚡️ perf', name: '性能：提升性能' },
  { value: '💩 optimize', name: '优化：代码优化' },
  { value: '⚰️ dead', name: '删除：废弃代码' },
  { value: '🔒 security', name: '安全性更新：安全性修复或更新' },
  { value: '🔗 deps', name: '依赖更新：更新依赖库或包' },
  { value: '⚙️ config', name: '配置：配置文件的更改' },
  { value: '📡 deploy', name: '部署：与项目部署相关的更改' },
  { value: '📦️ release', name: '发布：发布新版本' },
  { value: '🗄️ migrations', name: '数据迁移：数据库或数据相关的更改' },
  { value: '🖌️ ui', name: '用户界面：调整和更改' },
  { value: '🏷️ i18n', name: '国际化：多语言国际化相关更改' },
  { value: '♿ a11y', name: '可访问性：提升产品的可访问性' },
  { value: '✅ test', name: '测试：添加或更新测试' },
  { value: '🚧 wip', name: '开发中：尚未完成' },
  { value: '🚀 chore', name: '工具：开发工具变动 (构建、脚手架工具等)' },
  { value: '🔄 workflows', name: '工作流：CI 配置、脚本，等工作流相关文件更改' },
  { value: '💻 dev', name: '开发环境：开发工具、环境配置更改' },
  { value: '🏭 prod', name: '生产环境：生产环境配置更改' },
  { value: '⏪ revert', name: '回滚：代码回退' },
  { value: '⌛ merge', name: '合并：合并代码' },
  { value: '📝 changelog', name: '更新日志：更新 changelog' },
  { value: '⚗️ experiments', name: '实验性：实验性功能，可能存在错误等未知问题' },
  { value: '📜 license', name: '版权或许可证：添加或更新许可证' },
  { value: '👀 review', name: '代码审查：修改代码审查建议' },
  { value: '🥚 egg', name: '彩蛋：小惊喜' },
  { value: '🌐 network', name: '网络：网络请求、通信相关的更改' },
  { value: '📂 file', name: '文件操作：添加、删除、移动文件' }
];
